version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    environment:
      - DATA_DIR=data
      - DEBUG=true
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./scripts/nginx-dashboard:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/html
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  data:
